const fs = require("fs/promises");
const path = require("path");
const { execFileSync } = require("child_process");

const projectRoot = path.resolve(__dirname, "..");
const blueprintPath = path.join(projectRoot, "bag.bp");
const aigcRoot = path.join(projectRoot, "aigc");
const manifestPath = path.join(aigcRoot, "generated-assets.json");

function parseBlueprintResources(content) {
  return content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("- res://assets/"))
    .map((line) => line.slice(2).trim().replace(/^res:\/\//, ""));
}

async function main() {
  const blueprint = await fs.readFile(blueprintPath, "utf8");
  const resources = parseBlueprintResources(blueprint);

  if (resources.length === 0) {
    throw new Error("bag.bp does not declare any asset resources.");
  }

  execFileSync(process.execPath, [path.join(__dirname, "prepare_bag_aigc.js")], {
    cwd: __dirname,
    stdio: "inherit"
  });

  execFileSync(process.execPath, [path.join(__dirname, "generate_bag_assets.js")], {
    cwd: __dirname,
    stdio: "inherit"
  });

  execFileSync(process.execPath, [path.join(__dirname, "run_generate_bag_ui.js")], {
    cwd: __dirname,
    stdio: "inherit"
  });

  const assets = await Promise.all(
    resources.map(async (resource) => {
      const fullPath = path.join(projectRoot, resource.replace(/\//g, path.sep));
      const stat = await fs.stat(fullPath);
      const fileName = path.basename(resource, path.extname(resource));
      const promptPath = path.join(aigcRoot, "prompts", `${fileName}.txt`);
      const promptExists = await fs
        .access(promptPath)
        .then(() => true)
        .catch(() => false);

      return {
        resource: `res://${resource.replace(/\\/g, "/")}`,
        sizeBytes: stat.size,
        modifiedAt: stat.mtime.toISOString(),
        promptPath: promptExists
          ? `application/godot_inventory/aigc/prompts/${fileName}.txt`
          : null,
        source: "build:bag-ui",
        generationMode: "deterministic-node-canvas"
      };
    })
  );

  await fs.mkdir(aigcRoot, { recursive: true });
  await fs.writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        blueprint: "bag.bp",
        generatedAt: new Date().toISOString(),
        note: "These assets are generated by the existing deterministic Node/Canvas scripts. No external AIGC model is invoked by build:bag-ui.",
        aigcTaskPackPrepared: true,
        generatedScene: "res://scenes/bag_ui.tscn",
        assetCount: assets.length,
        assets
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  console.log(`Built bag UI pipeline and recorded ${assets.length} generated assets.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
